version: '3.8'

services:
  phip-backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=production
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-here}
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/api/health')" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
  # Optional: Add PostgreSQL for production
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: phip
  #     POSTGRES_USER: phip
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-secure-password}
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   restart: unless-stopped

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   restart: unless-stopped

  # volumes:
  #   postgres_data:

networks:
  default:
    name: phip-network
